version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:8.11.1-stretch

    steps:
      - checkout

      - run:
          name: Show current branch
          command: echo ${ CIRCLE_BRANCH }

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Install npm
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: 
      #  name: Run tests
      #  command: npm run test

      #- run: 
      #  name: Building
      #  command: |
      #    if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #      npm run build-prod
      #    else
      #      npm run build-dev
      #    fi
        
      #-save_cache:
      #  key: v1-dist-{{ .Environment.CIRCLE_BRANCH}}-{{ .Environment.CIRCLE_SHA1 }}
      #  paths:
      #    - dist


